[package]
name = "mailer-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
dotenv = "0.15"
log = "0.4"
env_logger = "0.10"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lettre = { version = "0.10", features = ["tokio1-native-tls"] }
redis = { version = "0.23.0", default-features = false, features = ["tokio-comp", "connection-manager"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
rev_lines = "0.3.0"

