# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "core/src/schema.rs"

[migrations_directory]
dir = "resources/migrations"
