version: '3.8'

services:
  user-service:
    container_name: mailer-user-service
    restart: always
    build:
      context: .
    command: user
    env_file:
      - .env
      - apps/user/.env
    environment:
      TZ: "${MAILER_TIMEZONE}"
    volumes:
      - "${MAILER_DOCKER_VOLUME_PATH}/uploads:/var/www/mailer/static/uploads"
    ports:
      - "${MAILER_DOCKER_DNS_PREFIX}.1:4401:4401"
      - "${MAILER_DOCKER_PRIVATE_IP}:4401:4401"
    networks:
      - mailer-main
    dns:
      - "${MAILER_DOCKER_DNS_PUBLIC_1}"
      - "${MAILER_DOCKER_DNS_PUBLIC_2}"
      - "${MAILER_DOCKER_DNS_PREFIX}.254"
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://user-service:4401/system/docker-health-check" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "50"

  executor-service:
    container_name: mailer-executor-service
    restart: always
    build:
      context: .
    command: executor
    env_file:
      - .env
      - apps/executor/.env
    environment:
      TZ: "${MAILER_TIMEZONE}"
    ports:
      - "${MAILER_DOCKER_DNS_PREFIX}.1:4402:4402"
      - "${MAILER_DOCKER_PRIVATE_IP}:4402:4402"
    networks:
      - mailer-main
    dns:
      - "${MAILER_DOCKER_DNS_PUBLIC_1}"
      - "${MAILER_DOCKER_DNS_PUBLIC_2}"
      - "${MAILER_DOCKER_DNS_PREFIX}.254"
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://executor-service:4402/system/docker-health-check" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "50"

networks:
  mailer-main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${MAILER_DOCKER_DNS_PREFIX}.0/24"
